/*
Navicat MySQL Data Transfer

Source Server         : localhost2018
Source Server Version : 100136
Source Host           : localhost:3306
Source Database       : sial

Target Server Type    : MYSQL
Target Server Version : 100136
File Encoding         : 65001

Date: 2019-06-11 17:26:20
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for rutas
-- ----------------------------
DROP TABLE IF EXISTS `rutas`;
CREATE TABLE `rutas` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `clientes` int(10) unsigned NOT NULL,
  `facturador` int(11) NOT NULL,
  `nombre` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lugar_exp` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `origen` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remitente` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dom_remitente` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `recoge` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `valor_declarado` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `destino` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `destinatario` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dom_destinatario` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `entrega` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fecha_entrega` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cantidad` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `embalaje` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `concepto` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `material_peligroso` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `indemnizacion` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `importe` double NOT NULL,
  `asignacion_precio` int(10) unsigned NOT NULL,
  `obs` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dias_re` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `rutas_clientes_foreign` (`clientes`),
  KEY `rutas_asignacion_precio_foreign` (`asignacion_precio`),
  CONSTRAINT `rutas_asignacion_precio_foreign` FOREIGN KEY (`asignacion_precio`) REFERENCES `provedores` (`id`),
  CONSTRAINT `rutas_clientes_foreign` FOREIGN KEY (`clientes`) REFERENCES `clientes` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of rutas
-- ----------------------------
INSERT INTO `rutas` VALUES ('1', '4', '7', 'Emilie Hessel', 'Prof. Randy Homenick Jr.', 'Makenzie Bartoletti Jr.', 'Mollie Marquardt', 'Dr. Flavie Schinner DVM', 'Prof. Cruz Rippin', 'Viva Kozey', 'Kieran Lueilwitz', 'Rafaela Torphy IV', 'Mr. Jorge Turner II', 'Javonte Jast', 'Tom Ruecker', 'Prof. Zackary Tremblay', 'Ole Lehner', 'Isai Kautzer', 'Prof. Moshe Murphy Jr.', 'Milo Lehner DDS', '10', '6', 'Prof. Wilson Marks I', '4', '2019-06-11 18:41:26', '2019-06-11 18:41:26');
INSERT INTO `rutas` VALUES ('2', '4', '9', 'Antonietta Cormier', 'Magdalen Lesch', 'River Johnson', 'Felix O\'Kon', 'Dr. Maggie Mosciski', 'Tierra Monahan', 'Briana Franecki', 'Dr. Hunter Hane Jr.', 'Percy Miller', 'Miss Helena Kilback I', 'Rodrick Pollich', 'Ms. Maybell Balistreri', 'Trevor Schuster', 'Dr. Alfonso Nicolas PhD', 'Arlie Reynolds', 'Mrs. Darlene Dickinson DDS', 'Darrin Kerluke III', '4', '2', 'Brooke Schowalter I', '3', '2019-06-11 18:41:26', '2019-06-11 18:41:26');
INSERT INTO `rutas` VALUES ('3', '10', '7', 'Rozella Haag', 'Willard Spinka II', 'Guy Mayer PhD', 'Rosetta Marvin', 'Jonas Thompson', 'Ms. Sydnee Hettinger', 'Dr. Kari Nicolas', 'Judy Mohr', 'Destini Homenick DDS', 'Dr. Ignacio Leffler I', 'Ebba McLaughlin', 'Carmelo Crooks DDS', 'Idella Konopelski', 'Dr. Cristopher Boyle II', 'Mr. Melany Schimmel', 'Prof. Dustin Dibbert V', 'Verdie Cummings', '3', '5', 'Stewart Wilkinson', '2', '2019-06-11 18:41:26', '2019-06-11 18:41:26');
INSERT INTO `rutas` VALUES ('4', '5', '1', 'Verna O\'Conner', 'Laura Lockman', 'Tania Kutch', 'Mrs. Chelsea Bogisich V', 'Mr. Jessie Leffler', 'Franco Homenick', 'Prof. Hank Bashirian DVM', 'Laura Kirlin', 'Dr. Bradley Rempel DVM', 'Norbert Towne', 'Mr. Keith Walter III', 'Amari Jerde', 'Miss Maymie Kemmer Sr.', 'Deontae Skiles', 'Unique Ledner', 'Scotty Reynolds', 'Oral Bins', '7', '4', 'Dr. Jovani Murray', '3', '2019-06-11 18:41:26', '2019-06-11 18:41:26');
INSERT INTO `rutas` VALUES ('5', '6', '8', 'Lucio Kautzer Sr.', 'Werner Altenwerth', 'Elza Greenfelder', 'Gaetano Eichmann', 'Alana Senger Sr.', 'Amely Labadie', 'Mike Kautzer', 'Prof. Meda O\'Connell IV', 'Dr. Jacky Smitham IV', 'Adeline Rowe', 'Ms. Virgie Becker IV', 'Gust Feest V', 'Arne Rowe Sr.', 'Burnice Jast Jr.', 'Adrien Kerluke', 'Austen Rutherford', 'Mrs. Eldora Rau PhD', '4', '3', 'Prof. Sedrick Marquardt PhD', '4', '2019-06-11 18:41:26', '2019-06-11 18:41:26');
INSERT INTO `rutas` VALUES ('6', '2', '1', 'Dr. Ariel Macejkovic II', 'Leonor Cruickshank', 'Prof. Orville Stark', 'Cleo Huel', 'Miss Melissa Barrows PhD', 'Eloise Botsford MD', 'Alba Labadie', 'Hassie Schimmel', 'Arlo Osinski', 'Pearlie Bashirian', 'Dr. Koby Upton', 'Lori Weissnat DDS', 'Alysha Renner', 'Mr. Marshall McLaughlin', 'Giovanni Gaylord V', 'Ms. Filomena Ward', 'Prof. Alana Gutmann', '6', '10', 'Delpha Kunze', '3', '2019-06-11 18:41:26', '2019-06-11 18:41:26');
INSERT INTO `rutas` VALUES ('7', '7', '7', 'Cleveland Johnston', 'Dr. Kayleigh Cartwright', 'Whitney Yundt', 'Ervin Lebsack', 'Davonte Pacocha', 'Joesph Marks', 'Pierre Wehner', 'Elda Stehr', 'Donny Barton', 'Adolph Terry', 'Krystina Collins', 'Nicolette Hahn', 'Herminia Kub', 'Mr. Reagan Rath III', 'Wilhelm Padberg', 'Will Hackett', 'Diana Conroy', '6', '9', 'Nia Hauck', '2', '2019-06-11 18:41:26', '2019-06-11 18:41:26');
INSERT INTO `rutas` VALUES ('8', '1', '9', 'Verona Hegmann', 'Prof. Maybell Howell I', 'Mr. Miguel Mohr', 'Vicky Hauck', 'Broderick Powlowski', 'Brandon Cassin', 'Mrs. Minerva Hackett', 'Nora Dicki', 'Prof. Virginia Tillman', 'Mr. Emil Grimes IV', 'Constantin Schaden', 'Dr. Jace Crona', 'Richard King', 'Tyrese Rutherford', 'Makayla Torp I', 'Muriel Hoppe III', 'Mara Moore III', '3', '10', 'Travis Kiehn PhD', '3', '2019-06-11 18:41:26', '2019-06-11 18:41:26');
INSERT INTO `rutas` VALUES ('9', '8', '7', 'Mr. Stanley Schuster', 'Mrs. Ursula Sipes DVM', 'Elinore Koelpin V', 'Vernie Fadel', 'Dr. Audie Walsh MD', 'Emmet VonRueden', 'Cindy Keeling', 'Alvina Weissnat', 'Maymie Raynor', 'Russel Bartoletti', 'Grant Daugherty', 'Christopher Oberbrunner', 'Perry Wisoky PhD', 'Prof. Shanny Schaefer III', 'Aurelia McKenzie', 'Sarah Adams DVM', 'Rhiannon Kuvalis', '7', '2', 'Mya Beatty', '3', '2019-06-11 18:41:26', '2019-06-11 18:41:26');
INSERT INTO `rutas` VALUES ('10', '5', '8', 'Fletcher Johnston', 'Ray Rutherford DDS', 'Assunta Hahn III', 'George Kling Sr.', 'Mr. Estevan Franecki DDS', 'Granville Casper', 'Camila Ziemann', 'Mrs. Delta Sauer', 'Mr. Brycen Durgan PhD', 'Mr. Geovanni Willms', 'Miss Ofelia Lang', 'Dahlia Klocko', 'Nona Schmeler', 'Isaias Walker', 'Cody Leuschke', 'Randall Torp', 'Kaitlyn Hoppe', '8', '9', 'Tyra Kemmer', '1', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('11', '7', '8', 'Miss Jude Jacobi', 'Donnell Rath', 'Zack Langosh', 'Fleta Weber', 'Prof. Angel Bergnaum DDS', 'Elmira Bernier', 'Prof. Ruby Beer', 'Dr. Adah Legros', 'Dr. Frances Mohr', 'Prof. Donny Kerluke', 'Mabelle O\'Kon', 'Nina Kiehn', 'Dr. Unique Abernathy', 'Chase Kirlin', 'Tyrell Orn', 'Keenan Heaney DDS', 'Connor McGlynn', '5', '9', 'Prof. Ewald Cole', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('12', '8', '9', 'Lula Feest IV', 'Mrs. Asha Schinner', 'Troy Wolf', 'Dr. Ramiro Leffler PhD', 'Carleton Mitchell', 'Evert Wilderman PhD', 'Diamond Boyer I', 'Karlee Hickle PhD', 'Anne Nicolas', 'Roma Bernier', 'Lonnie Hoppe', 'Audie Ankunding', 'Tamara Connelly', 'Jakob Stanton', 'Aniyah Rosenbaum', 'Reagan Luettgen', 'Shyann Morar', '6', '9', 'Randall Pacocha', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('13', '1', '8', 'Ms. Pasquale Schamberger', 'Madisyn Kautzer', 'Dr. Ray Rempel Sr.', 'Demetris Robel', 'Catharine Cormier', 'Stephania Wolf', 'Jamar Bruen', 'Jarrod Hickle DVM', 'Lew Larkin', 'Prof. Vilma Gutmann IV', 'Prof. Thomas Wisoky V', 'Abe Kemmer', 'Jaydon Gibson', 'Joy Gottlieb', 'Rozella Langosh III', 'Kathlyn Morissette', 'Garrison Howell', '1', '7', 'Mr. Vince Hagenes MD', '1', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('14', '5', '7', 'Jeramy Rempel', 'Wendell Kris Sr.', 'Janae Runte', 'Deja Krajcik', 'Waylon Gerhold DVM', 'Prof. Alysa Wiza DVM', 'Kaela Christiansen MD', 'Macey Stoltenberg', 'Mr. Braulio Gerhold', 'Autumn Gutmann', 'Prof. Carley Collier', 'Mr. Lonny Rippin DVM', 'Kiana Ullrich', 'Mrs. Pat Effertz', 'Connie D\'Amore I', 'Sydni Tillman III', 'Ruth Marks III', '3', '6', 'Dr. Sandy Cole MD', '4', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('15', '10', '2', 'Mr. Jadon Hagenes', 'Trisha Metz', 'Otha Shanahan DVM', 'Kamren Moen DVM', 'Ms. Jordane Bauch I', 'Fabian Emard', 'Joseph Fadel', 'Sadie Luettgen Sr.', 'Hershel Maggio', 'Miss Antoinette Luettgen', 'Foster Kris', 'Elise Moore', 'Imogene Romaguera I', 'Niko Flatley', 'Bernadine Schoen I', 'Kacie Schneider', 'Halie Koepp', '7', '9', 'Nigel Donnelly', '3', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('16', '8', '5', 'Elwyn Jacobs MD', 'Kirsten Hansen II', 'Derick Kuhn', 'Prof. Hildegard Abernathy Jr.', 'Mr. Judge Batz III', 'Dr. Theo Daniel', 'Miss Leonor Funk Jr.', 'Brooke Gottlieb', 'Kelley Welch', 'Ms. Eden Shanahan', 'Camron Buckridge', 'Maritza O\'Hara', 'Erick Corkery', 'Alessandro Watsica PhD', 'Christa Crooks', 'Gia Sporer', 'Nova Wuckert Sr.', '7', '8', 'Nadia Murphy PhD', '3', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('17', '8', '4', 'Spencer Walker', 'Mr. Connor Pouros DVM', 'Santa Shanahan I', 'Mitchel Jast', 'Norwood Daniel', 'Mr. Ernest Wyman V', 'Dr. Karelle Larson I', 'Prof. Darian Reynolds IV', 'Mr. Jarvis Lind DDS', 'Isaiah Funk', 'Skye Gottlieb', 'Bryana Ernser', 'Lula Yundt', 'Darius Koch', 'Eliane Farrell', 'Conrad Hegmann', 'Prof. Bennett Goodwin IV', '3', '10', 'Claudia Waters', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('18', '7', '8', 'Emely Howe', 'Maryse Lubowitz', 'Dessie Koss', 'Ardith VonRueden', 'Kimberly Carroll', 'Prof. Zackery Spinka I', 'Gwen Bailey', 'Delfina Bauch', 'Lauriane Bechtelar I', 'Tressa Koelpin', 'Otilia Durgan', 'Myrl Runolfsdottir', 'Claude Carroll', 'Monty Price', 'Carli Block', 'Ms. Antoinette Gorczany Jr.', 'Mr. Alford Volkman II', '3', '9', 'Dante Gorczany', '3', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('19', '1', '8', 'Chasity Gerlach', 'Jayden Powlowski', 'Nora Veum', 'Mr. Giles Sauer', 'Harmony Turcotte', 'Madeline King', 'Nils Champlin', 'Alaina Osinski', 'Ms. Alanna Casper', 'Wilmer Spencer', 'Antone Barrows', 'Leo Ziemann', 'Eriberto Parker', 'Mr. Amir Satterfield V', 'Shakira Kemmer', 'Yolanda Dare', 'Nasir Kautzer', '4', '3', 'Hannah Murphy', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('20', '6', '5', 'Ottis Jerde', 'Margarette Graham', 'Ms. Loren Osinski', 'Shannon Ward', 'Coby O\'Keefe', 'Mr. Justyn Cronin', 'Miss Tessie Turner DVM', 'Amelie Schamberger I', 'Miss Adella Bins Sr.', 'Mr. Niko Block', 'Dr. Wallace Stark I', 'Rosalee Roob', 'Hilda Douglas', 'Natalia Kautzer', 'Santina Kuphal', 'Cielo Terry', 'Alvis Murphy', '4', '9', 'Sofia Hagenes PhD', '1', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('21', '6', '1', 'Greg Prohaska', 'Lee Hessel', 'Mr. Stan Stracke', 'Miss Viva Little', 'Aditya O\'Hara', 'Dr. Michael Bogan V', 'Elinore Hegmann', 'Lyla Gerhold', 'Blake Krajcik', 'Kamille Spencer', 'Shakira Von', 'Dr. Eveline Daniel', 'Dr. Loraine Konopelski DDS', 'Nikolas Morissette', 'Stanford West Jr.', 'Camila Reinger', 'Prof. Elise Olson', '9', '6', 'Addison Schimmel I', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('22', '10', '1', 'Wilber Lubowitz', 'Christy Macejkovic', 'Emanuel Tromp Sr.', 'Octavia Roob Jr.', 'Ms. Rylee Schneider DVM', 'Prof. Gretchen Cartwright', 'Brayan Hettinger III', 'Virgie Considine', 'Mr. Kayleigh DuBuque V', 'Leslie Kovacek', 'Zechariah Langosh', 'Cordelia Fay', 'Montana Thiel PhD', 'Miss Hellen Brown', 'Elvie Brakus', 'Dasia Torphy', 'Lori Bernier', '3', '9', 'Dr. Jon Terry', '3', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('23', '9', '8', 'Morton Borer', 'Katelyn Farrell', 'Miss Nona Torphy III', 'Anna Grant', 'Sean Ullrich', 'Royal Ward', 'Tristin McDermott', 'Mr. Lyric Fritsch', 'Maritza Zemlak V', 'Gerda Ruecker', 'Ms. Kamille Murazik Jr.', 'Camille Weissnat II', 'Hassie Willms', 'Marie Rolfson', 'Tyler O\'Kon', 'Maribel Wiza', 'Thea Effertz', '8', '8', 'Ms. Lavada Rice IV', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('24', '6', '2', 'Linnea Koepp III', 'Reta Treutel', 'Jody Quigley III', 'Garland Swaniawski', 'Dr. Quentin Mante DVM', 'Bernie Murazik', 'Prof. Vernice Strosin', 'Dr. Clarabelle Baumbach PhD', 'Ms. Margarita Kunze DDS', 'Bonita Turcotte', 'Kaleigh Tillman DDS', 'Miss Christy Labadie', 'Cleo Hammes I', 'Prof. Colten Pfeffer Jr.', 'Alda Miller', 'Lacey Dare', 'Jayde Hansen', '5', '8', 'Carlo Goodwin', '1', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('25', '2', '3', 'Celestine Shields', 'Dr. Jamey Greenfelder', 'Edd Wisozk', 'Libbie Konopelski DDS', 'Gregg Jast', 'Mekhi Bosco I', 'Johathan Bosco MD', 'Mrs. Florine Daugherty', 'Jimmie Hintz IV', 'Mrs. Kaya Lakin PhD', 'Mr. Alfred Hickle', 'Mr. Axel Homenick DDS', 'Dena Tillman IV', 'Renee Cassin', 'Silas Mante', 'Cynthia McGlynn Jr.', 'Rudolph Leffler', '10', '3', 'Lincoln Lueilwitz', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('26', '8', '3', 'Birdie Welch PhD', 'Mrs. Rowena McGlynn Sr.', 'Prof. Casandra Ritchie Sr.', 'Kaylie Keebler', 'Marvin Weber', 'Mrs. Eleanora Reynolds Jr.', 'Katrine Schiller', 'Dr. Jaden Johns DDS', 'Mr. Dominic Schaden', 'Prof. Rosanna Smitham', 'Marina Prosacco', 'Prof. Bobby Grimes', 'Dr. Alford Flatley Jr.', 'Orville Kemmer', 'Prof. Xavier Altenwerth', 'Vance Cummings MD', 'Prof. Valentina Quigley IV', '9', '5', 'Emely Greenholt', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('27', '6', '1', 'Jena Anderson', 'Beulah Franecki', 'Dr. Molly Runolfsson', 'Carleton D\'Amore', 'Jonathan Bartoletti', 'Lemuel Shields', 'Prof. Felicity Will', 'Prof. Norberto Hudson', 'Mrs. Faye Langosh III', 'Gabriella Dickens', 'Prof. Brendan Metz', 'Ericka McGlynn', 'Gia Rippin', 'Elody Goyette', 'Miss Yessenia Blanda', 'Madisen Dicki', 'Carolyne Rohan', '2', '6', 'Griffin Witting', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('28', '5', '4', 'Onie Dach', 'Mrs. Mercedes Ortiz', 'Orie Hartmann', 'Mozell Frami', 'Quinton Schiller', 'Mikel Hackett', 'Vinnie Miller', 'Deven Hintz', 'Dr. Darian Stokes I', 'April Halvorson', 'Lavern Bartell', 'Kayley Pollich', 'Prof. Colleen Mertz', 'Randal Steuber', 'Sharon Rath', 'Maxime McLaughlin', 'Dr. Vicenta Kuvalis', '6', '5', 'Dominic Littel', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('29', '7', '5', 'Joanny Hill', 'Sheldon Schroeder', 'Rollin Grant', 'Prof. Willis Klocko PhD', 'Reilly Bayer', 'Mariano Ullrich', 'Justice Reinger', 'Mr. Jerel Yost IV', 'Prof. Rocio Brakus Jr.', 'Nasir Morissette', 'Sylvan Langosh', 'Prof. Cordelia Stiedemann', 'Afton Roob', 'Casimir Muller', 'Torrey Stiedemann', 'Prof. Zola Murazik III', 'Pearlie Kozey', '4', '8', 'Janae Feeney Sr.', '4', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('30', '10', '9', 'Leland Towne', 'Eliezer Borer', 'Viva Bergstrom', 'Roosevelt Blick', 'Angelita Weber Jr.', 'Hilbert Barton Sr.', 'Brandy Conn', 'Edgar DuBuque', 'Dr. Mitchel Purdy', 'Prof. Merritt Brakus I', 'Prof. Cindy Wilderman IV', 'Alf Mann', 'Ernesto Casper', 'Deion Lockman DVM', 'Tess Ward', 'Prof. Jonas Hessel MD', 'Prof. Celestine Gottlieb DVM', '6', '2', 'Rogelio Johnson DDS', '5', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('31', '5', '6', 'Mrs. Michelle Bergstrom I', 'Micaela Rogahn', 'Marcelle Lynch', 'Kariane Reilly DDS', 'Destin Satterfield', 'Rickie Kuhn', 'Yvonne Goldner', 'Prof. Deonte Lockman I', 'Bianka Macejkovic', 'Prof. Joanny Runte I', 'Madisyn Greenfelder', 'Mathias Lesch', 'Ms. Chloe Harvey', 'Lily Hirthe V', 'Stefan Wyman', 'Katarina Hoeger', 'Mr. Jeff O\'Kon II', '10', '3', 'Yasmine Goodwin II', '3', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('32', '9', '6', 'Amos Hane V', 'Miss Margarette Predovic III', 'Andres Hirthe', 'Jackeline Bradtke', 'Mr. Amani Ankunding', 'Dr. Electa Kuvalis V', 'Miss Lupe Donnelly', 'Vernice Morar', 'Royal Schneider DDS', 'Dr. Myrtice Rodriguez', 'Dr. Ibrahim Padberg V', 'Howard Wintheiser', 'Terrence Rau', 'Demarco Schimmel', 'Mrs. Pink Kreiger V', 'Prof. Ova Baumbach PhD', 'Lourdes Klocko', '1', '5', 'Maximillian Rohan', '1', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('33', '8', '8', 'Dr. Oma Buckridge DVM', 'Dr. Percival Kiehn MD', 'Ella Schneider', 'Tatyana Kub', 'Abigail Ankunding', 'Dr. Trenton Shanahan V', 'Prof. Vallie O\'Connell DDS', 'Prof. Callie Fahey', 'Mrs. Name Brekke', 'Prof. Geoffrey Armstrong', 'Ms. Beverly Weber V', 'Prof. Jerel Oberbrunner', 'Lacy Lehner', 'Mr. Ryan Tromp', 'Spencer Keeling', 'Keon Purdy', 'Mary Gutmann I', '9', '5', 'Marlon Corwin', '3', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('34', '7', '10', 'Jaquan Purdy III', 'Mr. Jermey Eichmann V', 'Holly Friesen', 'Prof. Sylvan Nienow', 'Ms. Karine Hand', 'Maddison Kulas', 'Nakia Adams', 'Fabiola Sanford', 'Miss Charlotte Moen MD', 'Kaia Walter', 'Prof. Chaya Funk MD', 'Verla Stanton', 'Dr. Raphael Bergnaum Sr.', 'Jarod McKenzie', 'Lacey O\'Kon', 'Dr. Durward Pouros', 'Lila Romaguera', '6', '1', 'Mrs. Dessie Schaden', '3', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('35', '1', '6', 'Mr. Halle Marvin MD', 'Ms. Leanne Erdman', 'Iliana Schoen II', 'Nikko Murray', 'Kip Parker', 'Idell Eichmann III', 'Jerrod Anderson', 'Dr. Dedric Quitzon III', 'Demetris Purdy DDS', 'Dr. Jaleel Lehner', 'Tony Blanda', 'Dr. Zora Hill III', 'Margarett Kling', 'Ara Kutch', 'Iliana Heller', 'Soledad Murazik', 'Angelina Jacobson', '1', '8', 'Dr. Jermain Leuschke III', '4', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('36', '5', '10', 'Miracle Maggio V', 'Mr. Cristopher Heathcote', 'Zaria Welch', 'Julio Renner V', 'Mr. Joe Reinger I', 'Joanie Fisher', 'Marcelo Aufderhar', 'Prof. Genevieve Mills', 'Gregorio Hand', 'Mrs. Lucile Bechtelar I', 'Dr. Jonathon Ratke PhD', 'Delpha Predovic', 'Mr. Tristin Kunde DVM', 'Brennan Heathcote DVM', 'Carlee Bode', 'Wilford Harber', 'Carol Hamill', '7', '4', 'Sigrid Dietrich IV', '5', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('37', '9', '9', 'Reilly Wilkinson I', 'Rocky Kulas', 'Prof. Ashlynn Emard', 'Kyleigh Kohler III', 'Mr. Hipolito Ondricka II', 'Carolyn Kautzer', 'Norma Reilly', 'Dr. Mallie Collins', 'Pink Howell MD', 'Idell Kshlerin', 'Miss Nicolette Koepp Jr.', 'Mustafa Jacobs Sr.', 'Lowell Kulas', 'Kyleigh Cole', 'Mr. Terry Koepp', 'Angela Weimann', 'Ben Kovacek Jr.', '4', '8', 'Pearline Kautzer', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('38', '4', '5', 'Leopold Rau', 'Elliot Lockman', 'Prof. Otho O\'Conner', 'Prof. Murphy Auer', 'Wilhelmine Mann', 'Kelli Stehr', 'Kelvin Blick', 'Miss Creola Simonis', 'Avis Buckridge III', 'Mr. London Smitham', 'Mr. Lonny Wyman PhD', 'Vicky Funk', 'Korbin Pagac', 'Archibald Ziemann MD', 'Mrs. Alice Moen', 'Akeem Konopelski', 'Leopoldo Mante', '3', '2', 'Caleb Russel', '4', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('39', '8', '6', 'Herminia Braun', 'Toney Hamill', 'Marcia Tromp', 'Miss Martine Streich III', 'Rosa Kshlerin', 'Mrs. Ashlee Marks DDS', 'Thomas Marks', 'Raegan Bashirian', 'Willis Hyatt', 'Ricky Abshire II', 'Casimer Pacocha', 'Edmund Lubowitz', 'Mr. Monte Boyle', 'Prof. Lavonne Stanton', 'Delaney Luettgen IV', 'Mr. Gordon Dare V', 'Hardy West', '5', '1', 'Ms. Bella O\'Reilly', '4', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('40', '4', '10', 'Kaela Lowe', 'Crawford Hamill', 'Sidney Kiehn', 'Prof. Victor Bernier Jr.', 'Dr. Verdie Johns', 'Thomas Rath', 'Dr. Bill Bosco I', 'Karson McCullough', 'Mr. Zachariah Rath', 'Blaise Greenfelder', 'Glen Huel', 'Maxime Marvin', 'Miss Janice Schmidt', 'Damion Huels', 'Telly Lynch', 'Dr. Ernestine Erdman DVM', 'Caitlyn Blanda', '3', '4', 'Myrtle Botsford', '1', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('41', '3', '1', 'Presley Ernser', 'Georgianna Glover', 'Boyd Schumm MD', 'Maudie Maggio', 'Dedric Morissette', 'Eden Heller', 'Miss Nora Hyatt', 'Antonietta Howe', 'Orlo Cormier', 'Mercedes Gutmann', 'Mr. Junior Nicolas MD', 'Dr. Karine Cummerata', 'Prof. Osbaldo Larkin III', 'Catherine Kuvalis', 'Columbus Legros', 'Mrs. Casandra Bernhard DDS', 'Bryana Eichmann', '3', '10', 'Curt Gibson', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('42', '10', '2', 'Adrianna Pfannerstill', 'Jacklyn Farrell', 'Jace Macejkovic', 'Prof. Roxanne Roob II', 'Cullen Schmitt', 'Mrs. Celia Leffler', 'Jeramy Runte', 'Catalina Lynch', 'Lenna Tillman V', 'Clara Jaskolski', 'Miss Cynthia Hegmann Sr.', 'Werner Borer', 'Deborah McGlynn', 'Mrs. Jaida Wolff', 'Crawford Klocko', 'Dr. Tiana Boyle PhD', 'Prof. Rolando Corwin II', '9', '4', 'Georgianna Mohr', '3', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('43', '6', '2', 'Ms. Loyce Shields IV', 'Mr. Eladio Hackett DDS', 'Jakayla Goldner', 'Liza Goodwin', 'Deja Macejkovic', 'Dandre Leffler', 'Miss Brooklyn Price DDS', 'Mireya Champlin', 'Dr. Joshua Stiedemann', 'Bartholome Rodriguez', 'Lou Schulist MD', 'Adrien Bogan', 'Prof. Eusebio Walter', 'Zachary Heidenreich', 'Price Hessel DDS', 'Mr. Kody Weissnat PhD', 'Edwin Hyatt', '9', '10', 'Rose Torp', '3', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('44', '4', '2', 'Miss Dawn Rodriguez', 'Piper Hilpert Jr.', 'Emmie Shields IV', 'Dr. Waino Dietrich II', 'Glenna D\'Amore', 'Grayce Rowe', 'Fanny Cremin', 'Daphnee Cremin DDS', 'Dr. Abigail D\'Amore', 'Eden Zieme', 'Dr. Coby Thompson II', 'Sheridan Bradtke', 'Clement Runolfsson', 'Ima Skiles', 'Mrs. Janie Pagac IV', 'Leatha Ritchie V', 'Ebony Prohaska', '5', '5', 'Miss Lupe Quitzon', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('45', '5', '7', 'Dustin Ortiz', 'Fern Goyette IV', 'Laurie Ryan V', 'Coralie Goldner', 'Shayne Hilpert', 'Emanuel Nikolaus', 'Bria Reinger', 'Alvis Jones', 'Dr. Koby Jacobs III', 'Michel Kovacek', 'Clovis Jenkins IV', 'Turner Trantow DVM', 'Stanford Rosenbaum', 'Prof. Ahmad Greenfelder', 'Dr. Laron Ledner PhD', 'Friedrich Cormier', 'Dee Brakus', '10', '6', 'Foster Weber', '4', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('46', '5', '1', 'Ms. Aniya Schumm', 'Oral Jaskolski', 'Cordia Gottlieb', 'Dee Walsh', 'Garland Baumbach', 'Dr. Zachery Runolfsson', 'Katrina Steuber', 'Savanna Carter', 'Hilbert Miller', 'Prof. Noble Hayes II', 'Zelda Jenkins Sr.', 'Dr. Darby Marquardt III', 'Mr. Lawson Keebler MD', 'Ms. Mollie Mohr', 'Sebastian Rosenbaum', 'Kariane Wisozk', 'Dr. Tyrese Reynolds V', '8', '5', 'Neil Donnelly IV', '2', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('47', '3', '7', 'Dr. Joel Heaney MD', 'Prof. Hope Christiansen MD', 'Delilah Buckridge MD', 'Dayna Konopelski', 'Jaqueline Renner MD', 'Genoveva Renner', 'Ursula Zieme', 'Dr. Lemuel McClure', 'Howard Kunde', 'Ms. Abigale Fay', 'Prof. Larissa Wisoky', 'Dr. Haylie Jacobson I', 'Alvera Haag', 'Emil Kilback', 'Mrs. Christy Quitzon', 'Bridget Crona Sr.', 'Ms. Bernadine Gerhold III', '1', '3', 'Prof. Jarod Johnson', '3', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('48', '2', '7', 'Kody Murphy', 'Ms. Lavada Langworth', 'Hollis Berge', 'Juwan Bruen', 'Mr. Erwin Johns', 'Margarett Hackett', 'Dennis Macejkovic', 'Cristopher Durgan', 'Prof. Myrtis Pacocha V', 'Dr. Eulalia Volkman PhD', 'Ramon Mitchell', 'Gerard Heathcote', 'Dr. Tremayne Ondricka III', 'Kayla Tremblay', 'Forrest Brakus', 'Baby Ondricka', 'Mrs. Melyna Yundt Sr.', '3', '9', 'Karolann Kiehn MD', '5', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('49', '7', '3', 'Dr. Garfield Watsica', 'Marco Hill', 'Mrs. Abbie Mohr DDS', 'Leonora Kuvalis', 'Prof. Prince Lockman IV', 'Newell Hilpert', 'Dr. Derek Cummings Jr.', 'Casandra Koepp', 'Ms. Kenna Schumm', 'Ms. Marie Cormier PhD', 'Kiley Kilback', 'Armand Blick', 'Dorcas Krajcik', 'Miss Liliane Satterfield II', 'Mr. Camron Runolfsdottir Sr.', 'Reba Herman', 'Wava Kuphal', '2', '8', 'Crawford Hansen', '5', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('50', '8', '5', 'Prof. Angelica Rutherford II', 'Kiana Pfannerstill', 'Miss Assunta Upton II', 'Jazlyn Fritsch', 'Elda Pouros', 'Mr. Merle Ritchie DVM', 'Prof. Cleo Murray', 'Mr. Kolby Howell', 'Myah Fritsch', 'Greg Hauck', 'Ardella Jacobson', 'Ms. Isabel Koelpin MD', 'Cleora Cruickshank', 'Imani Baumbach', 'Florian Hamill', 'Mr. Clifton Zboncak Jr.', 'Jonathon Roob', '4', '2', 'Furman Beatty', '1', '2019-06-11 18:41:27', '2019-06-11 18:41:27');
INSERT INTO `rutas` VALUES ('51', '48', '5', 'RUTAUNO', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', '5', '48', 'OK', '4', null, null);
