/*
Navicat MySQL Data Transfer

Source Server         : localhost2018
Source Server Version : 100136
Source Host           : localhost:3306
Source Database       : sial

Target Server Type    : MYSQL
Target Server Version : 100136
File Encoding         : 65001

Date: 2019-06-05 17:01:12
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for rutas
-- ----------------------------
DROP TABLE IF EXISTS `rutas`;
CREATE TABLE `rutas` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `clientes` int(10) unsigned NOT NULL,
  `nombre` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cliente` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lugar_exp` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `origen` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remitente` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dom_remitente` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `recoge` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `valor_declarado` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `destino` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `destinatario` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dom_destinatario` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `entrega` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fecha_entrega` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cantidad` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `embalaje` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `concepto` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `material_peligroso` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `indemnizacion` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `obs` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dias_re` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `rutas_clientes_foreign` (`clientes`),
  CONSTRAINT `rutas_clientes_foreign` FOREIGN KEY (`clientes`) REFERENCES `clientes` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of rutas
-- ----------------------------
INSERT INTO `rutas` VALUES ('1', '7', 'Giovanni Pacocha', 'Ms. Matilda Johnson Sr.', 'Prof. Kareem O\'Hara', 'Jerad Kilback IV', 'Hermina Yundt', 'Deshaun Boyle', 'Dr. Houston Koelpin', 'Benny Welch', 'Kariane White', 'Luis Adams III', 'Prof. Leann Hartmann', 'Miss Della Paucek', 'Victoria Hamill', 'Miss Kaylie Jacobs', 'Jana Stroman', 'Makenna Kuhic', 'Annabel Hegmann', 'Mr. Candido Yost', 'Diamond Fay', '5', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('2', '10', 'Miss Angelita Hansen', 'Prof. Casimir Pouros DVM', 'Lauriane Franecki', 'Kolby Volkman', 'Miss Kyla Ryan', 'Esteban Rau', 'Chadd Koepp', 'Prof. Neha Hill', 'Rhett Schowalter', 'Prof. Matt Mante MD', 'Tamia Purdy', 'Dr. Deondre Carter', 'Dr. Magnus Gleason', 'Berenice Johnston', 'Palma Lind', 'Cedrick Lehner', 'Delfina Feest', 'Prof. Krystal Jacobi', 'Maribel Nader IV', '1', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('3', '7', 'Mr. Toby Dibbert', 'Kariane Turner', 'Larry Muller DVM', 'Alison Gislason', 'Randall Koelpin V', 'Macy Wolff', 'Maureen Berge DVM', 'Frances Little', 'Arden Weimann', 'Prof. Lourdes Witting', 'Prof. Hilton Berge III', 'Mrs. Delfina Gleason', 'Miss Magdalena Sanford', 'Dr. Harry Murazik', 'Esther Crooks', 'Madisyn Champlin PhD', 'Prof. Matt Klein', 'Ruby Keeling', 'Dylan Roberts', '1', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('4', '9', 'Hermina O\'Keefe Sr.', 'Ms. Lelia Feeney', 'Adolphus Rutherford MD', 'Mr. Emil Marquardt', 'Morton Hermiston', 'Ms. Frieda Cruickshank DDS', 'Prof. Van Bahringer Sr.', 'Karolann Oberbrunner', 'Mr. Van Spencer I', 'Electa Luettgen', 'Yolanda Gulgowski', 'Evalyn Gutkowski', 'Cordia Senger', 'Nathen Stracke', 'Dr. Toby Lang V', 'Mrs. Mazie Olson', 'Kyleigh Gutmann', 'Paula Mosciski', 'Sadie O\'Connell', '4', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('5', '8', 'Dr. Lelia Tromp MD', 'Jovani Stehr III', 'Zander Hodkiewicz', 'Sophie Braun V', 'Raphael Daugherty', 'Prof. Talon Gutkowski', 'Jena Corwin', 'Ms. Gwendolyn Schuster', 'Andres Klocko', 'Braulio Rice', 'Miss Emmalee Torphy', 'Euna Botsford', 'Zoe Schuster II', 'Anita Fritsch', 'Mr. Lucio Jacobs MD', 'Dr. Oswald Harris Jr.', 'Rhoda Walter Sr.', 'Reymundo Torp', 'Ms. Winifred Lindgren', '5', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('6', '3', 'Noble Barrows', 'Mr. Jordyn Bashirian Sr.', 'Abdiel Heidenreich', 'Prof. Cordelia Bergnaum II', 'Eldora Schuppe Sr.', 'Garrett Carroll', 'Zakary Weber', 'Fred Batz', 'Marietta Langworth', 'Aryanna Huels', 'Prof. Theresa Gibson', 'Mr. Josh Gulgowski IV', 'Gerardo Hauck', 'Citlalli Kshlerin MD', 'Marjory King', 'Jodie Hackett', 'Kristopher Kreiger', 'Prof. Sierra Hodkiewicz', 'Dr. Randi Waelchi', '2', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('7', '3', 'Alda Reilly', 'Arne Johns', 'Ms. Vicky Green DDS', 'Arnaldo Cremin II', 'Ruth Moen', 'Joana Hartmann', 'Prof. Enos Marks', 'Prof. Gladys Bogan', 'Triston Fisher', 'Travon Rempel', 'Darrick Abernathy', 'Prof. Maribel Jacobson V', 'Idella Grady II', 'Viviane Nitzsche', 'Tod Hickle', 'Miss Brooklyn Douglas', 'Blair Macejkovic', 'Dr. Pink Dickinson DVM', 'Kailyn Schneider', '3', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('8', '3', 'Clara Bernier II', 'Akeem Fisher DDS', 'Tyrese Bosco', 'Dr. Clair King III', 'Dr. Rodrick Reilly I', 'Orland Wisozk', 'Nathanial Schmitt I', 'Myrtle Crona', 'Beverly Rippin', 'Prof. Herminia Tromp', 'Mr. Immanuel Bailey IV', 'Adrianna Wolff PhD', 'Garland Pollich', 'Dr. Anna Dooley', 'Mr. Trevion Armstrong III', 'Ms. Simone Lindgren DVM', 'Felton O\'Keefe Sr.', 'Constance Ziemann', 'Karson Farrell', '1', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('9', '8', 'Enrico Dibbert IV', 'Lora Wiza', 'Ms. Pansy Kertzmann Sr.', 'Blake Schuster', 'Hubert D\'Amore Sr.', 'Helga Sporer', 'Dr. Lurline Cassin', 'Mazie Medhurst', 'Prof. Neil Powlowski', 'Dr. Michael Swift', 'Mrs. Mae Daugherty IV', 'Mr. Camden Sipes', 'Gladys Maggio', 'Leonie Senger', 'Dr. Daron Walter', 'Prof. Osvaldo Erdman', 'Angelo Dach', 'Dr. Jeffery Beatty', 'Mrs. Retta Brown IV', '5', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('10', '6', 'Hardy Willms', 'Thalia Hansen Jr.', 'Isidro Bernhard', 'Edmond Heller', 'Crystal Macejkovic', 'Helena Trantow', 'Kaelyn Sawayn', 'Prof. Aron Morissette', 'Selina Wilkinson', 'Arvid Shanahan', 'Ms. Adell Grimes', 'Ansley Walsh', 'Mr. Pete Streich', 'Maria Erdman', 'Kayleigh Deckow', 'Esta Kovacek', 'Ms. Myrtice Okuneva', 'Judy Schinner', 'Missouri Johnson PhD', '2', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('11', '6', 'Consuelo Tromp', 'Mrs. Lyla Jakubowski DDS', 'Ines Fadel DVM', 'Dereck Osinski', 'Jayme Tremblay', 'Timmothy Goldner', 'Kian Considine', 'Rubie O\'Kon', 'Anibal Mueller', 'Prof. Calista McClure', 'Jarret Larkin', 'Ms. Ida Hand PhD', 'Dr. Kasandra Berge', 'Fabian Wuckert', 'Alexandrea Pfannerstill', 'Dr. Nia Jones II', 'Prof. Eloisa Ritchie MD', 'Dora Prohaska', 'Katharina Schimmel', '2', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('12', '1', 'Tracy Kunze', 'Henri VonRueden', 'Angus Lueilwitz IV', 'Destini Collins', 'Simeon Macejkovic', 'Aurore Corwin', 'Rosie Daniel', 'Corine Haley PhD', 'Alfred Bosco', 'Dr. Remington Macejkovic', 'Anika Skiles', 'Mrs. Gudrun Sauer PhD', 'Dr. Laverne Gottlieb', 'Mr. Blaise Klein II', 'Johnathan Williamson', 'Noah Graham V', 'Gunnar Quigley', 'Florine Hauck', 'Stephen Willms Jr.', '1', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('13', '1', 'Prof. Billy Moen', 'Ms. Susie Schmeler', 'Cayla Conn', 'Dr. Jeramie Fritsch', 'Miss Verdie Huel', 'Sigrid Farrell', 'Jessica Kautzer', 'Elta Bashirian', 'Mr. Guy Schowalter Sr.', 'Estell Johns', 'Miss Trudie Haley', 'Elza Waelchi', 'Mercedes Torp', 'Billy Walker', 'Jordane Blanda PhD', 'Rodrick Keeling', 'Dusty Wiza', 'Dr. Keara Koch', 'Ezra Stanton', '1', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('14', '2', 'Hillary Schaden III', 'Dr. Golda Ritchie', 'Isabell Gutmann', 'Nicolette Stamm Sr.', 'Talon Breitenberg V', 'Barrett Cruickshank MD', 'Prof. Cyril Purdy IV', 'Brenden Osinski', 'Beaulah Wisozk Sr.', 'Paige Harber', 'Corrine Olson', 'Ressie Aufderhar', 'Harmon Jakubowski', 'Etha Daniel', 'Frida Wisoky III', 'Dr. Jasper Haley', 'Eleanora Marks I', 'Mrs. Demetris Friesen', 'Jessyca Jacobson', '3', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('15', '3', 'Prof. Earline Dibbert', 'Ms. Noemie Luettgen', 'Dr. Roman Fay III', 'Hoyt Heaney', 'Ms. Itzel Dare', 'Patrick Steuber', 'Mrs. Rosanna Hansen III', 'Noe Gaylord', 'Lori Kautzer DVM', 'Loren Ledner MD', 'Savanna Sanford IV', 'Yazmin Gleichner', 'Prof. Garnett Considine MD', 'Dr. Pierce Hill IV', 'Natalie Gerlach', 'Saul Rippin', 'Antonio Grimes', 'Dorothea VonRueden', 'Mrs. Jessica Hilpert MD', '1', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('16', '10', 'Dr. Dedrick Dickens', 'Mrs. Celine Nitzsche', 'Mr. Ignatius Hickle I', 'Keven Hauck', 'Katelynn Feest', 'Brenna Wehner', 'Miss Gertrude Okuneva', 'Macie Russel', 'Bruce Blanda', 'Brook Langosh', 'Misael Williamson Jr.', 'Thalia Predovic', 'Jovanny Leuschke', 'Carley Haley', 'Einar Schmidt', 'Alda Stokes', 'Mrs. Destini Hettinger II', 'Maxwell Kilback', 'Otilia O\'Kon', '3', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('17', '7', 'Else Brown', 'Dr. Richie Conn PhD', 'Miss Julia Walsh III', 'Toni Reilly', 'Shemar Fisher', 'Virgie Robel', 'Mrs. Rowena Hudson', 'Mrs. Ethyl Green', 'Ladarius Cartwright', 'Mason Cartwright', 'Miss Elta Stamm', 'Gwen Kovacek', 'Mrs. Augustine Fay', 'Grace Kris', 'Michel Franecki', 'Ressie Lind', 'Lavina Herzog', 'Enoch Grant DVM', 'Prof. Christelle Collins III', '5', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('18', '1', 'Nathan Paucek', 'Berniece Marquardt', 'Michele Littel V', 'Emiliano Goyette', 'Flavio Pfannerstill IV', 'Rosalee Bruen', 'Karlee Walsh', 'Kathryne Hamill', 'Herbert Yost', 'Madge Cronin', 'Steve Weimann Sr.', 'Darian Mayer', 'Dr. Mortimer Osinski MD', 'Marquise Carroll', 'Dr. Pascale Jacobs', 'Abbey Langosh', 'Rosie Streich', 'Marcella Raynor', 'Keyon Schamberger', '2', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('19', '5', 'Emmie Thompson', 'Marco Mitchell', 'Harry Langworth', 'Sebastian Gusikowski', 'Dr. Frederik Bergnaum DVM', 'Meda Rolfson', 'Violette Hermann', 'Kirsten O\'Conner IV', 'Dr. August Turner III', 'Tre Kreiger', 'Leilani Deckow', 'Emilio Runte', 'Ezekiel Jacobs', 'Ms. Josephine Kling', 'Gennaro Schowalter', 'Jesse Strosin III', 'Kali Bogisich', 'Willow Torphy', 'Elza Wyman', '5', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('20', '2', 'Dr. Kay Davis DVM', 'Flavie Sipes', 'Summer Heller', 'Ms. Katherine O\'Connell', 'Dr. Bert Treutel', 'Dayne Reinger', 'Wilma Beatty', 'Randal Schowalter', 'Addie Littel', 'Immanuel Wintheiser', 'Ms. Karianne Larkin', 'Helmer Herzog', 'Breana Schoen', 'Anderson Gorczany', 'Rod Greenholt', 'Gladyce Flatley', 'Misty Grady', 'Dr. Aylin Upton V', 'Mariela Fay', '4', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('21', '6', 'Christopher Daniel DDS', 'Tristin Price', 'Lauryn Hill', 'Ariane Sauer', 'Arvilla Simonis', 'Dr. Magnolia Dare III', 'Miss Kaycee Nikolaus', 'Sofia Hyatt', 'Harrison Hintz', 'Drew Boyle', 'Branson Stokes', 'Dr. Lori Hackett DVM', 'Giovanna Lemke', 'Verna Bednar', 'Ms. Daphne King II', 'Oda Fahey PhD', 'Maximus Kulas', 'Neva Kohler IV', 'Russ Flatley', '3', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('22', '9', 'Mr. Lonzo Rogahn', 'Christa Rolfson', 'Donavon Schultz', 'Aurelio Huels', 'Prof. Lucienne Collins Sr.', 'Burdette Aufderhar', 'Prof. Kelvin Barrows V', 'Mohammad Pfannerstill V', 'Janie Lynch', 'Haylie Rosenbaum', 'Kody Connelly', 'Thaddeus Emard', 'Abdullah Murray', 'Mrs. Shirley Cruickshank', 'Dr. Jaylan Pollich DDS', 'Kendrick Koepp', 'Velma Farrell Jr.', 'Prof. Elton Heathcote', 'Dave Rosenbaum', '5', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('23', '4', 'Erling Rutherford IV', 'Mrs. Simone Murphy Sr.', 'Krystal Hessel', 'Gillian Heller', 'Miss Mercedes Gusikowski IV', 'Maria Windler', 'Ross McDermott Jr.', 'Joannie Schinner', 'Jarrell Roob', 'Ansel Kozey', 'Karl Koss', 'Dr. Greg Emmerich Sr.', 'Zachary Davis', 'Mr. Estevan Rosenbaum DDS', 'Prof. Stan Kemmer', 'Emmie Wuckert', 'Antonia Schuster', 'Katheryn Wilkinson', 'Sienna Beahan DVM', '2', '2019-06-05 19:17:11', '2019-06-05 19:17:11');
INSERT INTO `rutas` VALUES ('24', '3', 'Gerry Gaylord', 'Monte Deckow', 'Ulises Kshlerin', 'Cloyd McClure', 'Ken Fahey', 'Miss Sandy Reichel Sr.', 'Arvid Veum II', 'Dr. Darryl Reilly', 'Niko Vandervort V', 'Dr. Kayla Collins DDS', 'Tyson Terry', 'Mathias Ward MD', 'Mr. Rodolfo Koelpin', 'Prof. Kaitlyn Yost IV', 'Dr. Gerhard Ankunding', 'Brenden Kerluke DDS', 'Tito Koepp I', 'Dr. Lina Abernathy DVM', 'Enola Hill', '4', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('25', '2', 'Grayce Grimes', 'Elroy Cruickshank', 'Prof. Carmella Rutherford', 'Sylvester Herman', 'Yazmin Kassulke', 'Dr. Rosalinda Fadel', 'Prof. Izaiah Hermiston', 'Danika Gulgowski', 'Jaime Larkin', 'Dr. Lamar Treutel', 'Elnora Grant', 'Elmira Kuhlman', 'Eino Mayert', 'Albin Bailey', 'Ms. Kirsten Armstrong Sr.', 'Brooklyn Reichert Sr.', 'Prof. Gonzalo Gutkowski II', 'Emely Bogan III', 'Dejon Reinger', '4', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('26', '3', 'Camilla Nader', 'Dr. Anabelle Terry Sr.', 'Carlo Cartwright I', 'Prof. Cade Abshire', 'Maida Graham', 'Jeromy Denesik', 'Sammie Bode', 'Beaulah Schiller', 'Dewayne Kub', 'Telly Kunze', 'Mr. Kelley Wisoky', 'Gerald Lindgren III', 'Sim Ebert', 'Cletus O\'Hara', 'Reva Gaylord', 'Lucie Rice', 'Ms. Queenie Kessler', 'Elza Mitchell', 'Mrs. Georgiana Mante DDS', '4', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('27', '8', 'Ursula Jaskolski', 'Madalyn Witting IV', 'Fernando O\'Reilly', 'Carolanne Carter MD', 'Miss Birdie Oberbrunner', 'Jett Gottlieb', 'Noemy Lockman', 'Mr. Frederic Nienow', 'Brandy Hand', 'Prof. Bennett Harris DDS', 'Austin Doyle Jr.', 'Amina Pouros', 'Dr. Jarrell DuBuque', 'Mr. Broderick Dare', 'Ms. Aurore Emmerich', 'Trever Conn', 'Darlene Pouros', 'Ms. Mozell Gusikowski', 'Marcelino Rodriguez Jr.', '2', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('28', '5', 'Dario Friesen Sr.', 'Mallie Feil', 'Helmer Senger', 'Edd Rodriguez', 'Tyson Parker', 'Prof. Alyson Little MD', 'Miss Shana Dickens', 'Marianna Morissette', 'Arno Dare DVM', 'Curt Blanda', 'Alyson Goodwin Sr.', 'Paolo Miller Jr.', 'Moshe Grady', 'Prof. Rosalind Schroeder', 'Mrs. Dixie Krajcik IV', 'Ezequiel Hauck IV', 'Melyssa Kunde Jr.', 'Abbey Ullrich II', 'Colin Borer', '2', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('29', '10', 'Amari McCullough', 'Karley Beier', 'Mr. Deion Towne DVM', 'Elbert Casper', 'Rollin Daniel', 'Matilda Denesik', 'Mrs. Duane Volkman DDS', 'Adelle Dietrich', 'Mathias Pfeffer', 'Mrs. Cathrine Altenwerth MD', 'Gladyce Lindgren', 'Prof. Presley Reichel IV', 'Dr. Domenico Blanda V', 'Prof. Abraham Huels DVM', 'Prof. Frances Keeling', 'Eulah Herzog', 'Vladimir Cummerata', 'Dr. Kacey Tillman DVM', 'Ms. Maia Wilderman', '3', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('30', '3', 'Jarvis Mohr', 'Lurline Feil', 'Mrs. Bert Rowe', 'Elisha Stoltenberg DVM', 'Dennis Beier', 'Davin Braun', 'Dr. Bill Gutmann', 'Destiny Hoppe', 'Freddy Wuckert', 'Rico Ferry V', 'Dr. Benedict Ruecker V', 'Dr. Litzy Haley IV', 'Prof. Jose Bogisich', 'Esta Goldner I', 'Mrs. Lucinda Feil', 'Chad Considine', 'Percy Heaney', 'Dr. Liliana Swaniawski PhD', 'Mattie Cremin', '3', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('31', '1', 'Prof. Jamison Zulauf', 'Theo Jacobs MD', 'Prof. Dereck White', 'Evie Trantow', 'Mellie Ritchie', 'Lester Rohan V', 'Brady Runolfsson PhD', 'Dana Halvorson', 'Flavio Kassulke', 'Dr. Kaley Toy', 'Rey Murphy', 'Norwood Cruickshank Jr.', 'Ricardo Graham', 'Ashlee DuBuque', 'Dorcas D\'Amore', 'Zack Koch', 'Mrs. Kaia Reichert DVM', 'Trisha Huel', 'Margret Cole', '4', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('32', '8', 'Leta Funk', 'Pauline Ferry', 'Mylene Kihn', 'Sydney Schmidt', 'Mathias Turcotte MD', 'Oran Nolan', 'Reed Pfannerstill', 'Dr. Modesto Doyle DVM', 'Kaci Tromp', 'Prof. Jessika Schmeler Sr.', 'Orlo Howe PhD', 'Mrs. Cordia Larkin', 'Ms. Luisa Hamill I', 'Miss Kirsten Heller', 'Keon Mitchell V', 'Prof. Queen Hoppe', 'Miss Yesenia Mann DDS', 'Gretchen Wisozk', 'Vincenza King I', '1', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('33', '6', 'Minerva Von', 'Bridgette Nikolaus', 'Orin Waelchi III', 'Andreane Wiegand', 'Elyssa Willms', 'Carol Lakin', 'Lura Heaney', 'Dr. Ronny DuBuque', 'Mrs. Sienna McKenzie V', 'Laura Prosacco', 'Dr. Leif Sanford II', 'Marguerite Mills', 'Clementina Rogahn', 'Dylan Abbott', 'Diego Watsica', 'Brionna Kutch', 'Ms. Destany Fahey IV', 'Jefferey Moen PhD', 'Miss Brisa Brown III', '3', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('34', '4', 'Mohammed Carroll IV', 'Dr. Darron Gorczany', 'Miss Briana Ward', 'Hermann Ankunding', 'Alec Nader V', 'Isaias Hoeger', 'Aleen Kilback', 'Mrs. Myrtie Ortiz', 'Emie Cronin DDS', 'Mrs. Lilla Turner DVM', 'Amber Schultz III', 'Dr. Elijah Johns DVM', 'Jaylan Huel', 'Prof. Ernest Klein IV', 'Ronny Miller II', 'Candice Kerluke', 'Russell Brekke IV', 'Dr. Cielo Langworth', 'Christian Rowe', '4', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('35', '7', 'Mrs. Alysha Kuphal', 'Eileen Kuvalis', 'Omari Sauer', 'Mr. Zakary Hermann', 'Arvilla Rath III', 'Dr. Kassandra Kuhic', 'Mr. Jordon Yost', 'Harrison Feeney', 'Karina Smith', 'Dr. Jazlyn Quigley V', 'Toby Kassulke', 'Leora Cormier', 'Charity Howell', 'Evans Rosenbaum', 'Prof. Claude Bergnaum IV', 'Dr. Marco Bode', 'Prof. Nella Prohaska IV', 'Miss Mariam Botsford I', 'Prof. Elliott Brekke IV', '5', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('36', '7', 'Dianna McDermott', 'Shany Gaylord DVM', 'Easter Johns', 'Mr. Forrest Shields II', 'Karelle Satterfield', 'Prof. Mandy Funk', 'Zoey Jaskolski', 'Karine Yundt', 'Tyson Dooley', 'Prof. Ezequiel Funk DDS', 'Werner Conroy', 'Dr. Maybell Cole II', 'Rosendo Herman MD', 'Gilbert Lowe', 'Miss Elsa Casper I', 'Cordia McKenzie DDS', 'Leanne Cormier PhD', 'Orlando Kuhn', 'Prof. Bernardo Bahringer II', '3', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('37', '4', 'Hazel Fahey', 'Ashlynn Reynolds', 'Lela Bins', 'Dr. Marlin Braun MD', 'Darwin Nader', 'Lenore Paucek', 'Helen Gerhold', 'Corene Lang', 'Lucie Mann', 'Jamison Wiegand', 'Katrina Bauch', 'Ayden Medhurst', 'Kory Klocko', 'Mrs. Wendy Fritsch V', 'Winifred Hirthe', 'Jett Brekke', 'Mrs. Priscilla Wilderman', 'Dr. Liam McDermott V', 'Mrs. Jeanie Auer', '3', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('38', '7', 'Zena Rohan', 'Major Klocko', 'Evelyn Kutch', 'Mrs. Hannah Dooley I', 'Mrs. Micaela Hoppe III', 'Earlene Bradtke', 'Harmony Cronin', 'Dennis Barrows', 'Josie Becker', 'Chyna Pfeffer PhD', 'Prof. Lily Bayer I', 'Mr. Elian Herman V', 'Orion Wiza', 'Bernita Reichert', 'Tyreek Fay', 'Mrs. Adella Daniel Jr.', 'Miss Rosetta Huels', 'Mr. Julius Pollich IV', 'Mateo Collier', '4', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('39', '7', 'Prof. Abagail Carroll V', 'Cassidy Grant', 'Mr. Jamie Kuhn Jr.', 'Dr. Shad Stehr III', 'Kenton McCullough', 'Jairo Emmerich DDS', 'Elmo Jones', 'Anna Daniel', 'Chanel Kuhlman', 'Mr. Hiram Stoltenberg', 'Mr. Joaquin Bednar', 'Dr. Alverta Reilly', 'Aurore Larson III', 'Monserrate Beer', 'Kaitlyn Blanda', 'Art Stracke', 'Riley Schimmel', 'Mr. Camryn Stanton', 'Stefanie Connelly', '2', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('40', '5', 'Lucy Jacobson', 'Elmira Romaguera', 'Chelsie Goyette', 'Dr. Brenda Strosin', 'Tara Maggio', 'Colton Cremin', 'Marina Ratke DVM', 'Margaretta Toy', 'Daron Mohr Jr.', 'Dr. Shyanne Wiegand PhD', 'Kelsi Donnelly', 'Christophe Smitham', 'Madie Kling', 'Rickey Gottlieb Jr.', 'Prof. Mariela Baumbach V', 'Mr. Royce Borer Jr.', 'Rupert Kassulke', 'Mrs. Maiya O\'Kon DVM', 'Mr. Fredy Ziemann', '3', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('41', '4', 'Evelyn Gerhold', 'Horacio Funk', 'Aurelio Monahan MD', 'Mr. Rylan Cremin DVM', 'John Koelpin V', 'Isabel Tillman', 'Margarita Koelpin', 'Mrs. Lois Greenfelder V', 'Prof. Cesar Murazik', 'Missouri Hill', 'Yadira Sipes', 'Dr. Aliya Cassin', 'Isidro Barton', 'Dr. Desmond Kirlin II', 'Timothy Auer', 'Tania Anderson', 'Jeramie Hudson Jr.', 'Ian Bosco III', 'Mr. Tommie Marvin', '5', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('42', '3', 'Maureen Lehner', 'Mrs. Enola Wisozk', 'Elroy Robel Jr.', 'Dayana Carter', 'Prof. Jermaine Davis', 'Bailee Pollich', 'Nona Kuhlman', 'Kenny Brakus IV', 'Prof. Darrion Kautzer', 'Lillian Moen DVM', 'Xavier Wiegand', 'Dandre Pagac', 'Turner O\'Hara Jr.', 'Jay Dicki MD', 'Judge Dibbert', 'Ms. Alycia Williamson V', 'Alfreda Heidenreich', 'Pierce Sawayn', 'Ms. Bianka Lowe V', '3', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('43', '8', 'Juliana Frami', 'Bernadine Collier', 'Seth Nader', 'Janie Conn', 'Rosie Pacocha', 'Dr. Sheridan Koch III', 'Eula Brakus', 'Dr. Benny Lebsack', 'Mrs. Emilie Satterfield MD', 'Ms. Iva Leannon V', 'Esther Gottlieb PhD', 'Alexzander Okuneva', 'Eric Homenick', 'Prof. Leanne Abbott', 'Dolly Bogisich', 'Jenifer Langworth', 'Lucious Bruen', 'Darrell Runte', 'Prof. Mauricio Pagac', '3', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('44', '4', 'Norbert Hills', 'Mafalda Gibson', 'Jerry Bartoletti', 'Ashly Bogisich', 'Ms. Cheyenne Heaney II', 'Prof. Marian Bayer IV', 'Eino Konopelski III', 'Prof. Gregory Kris', 'Guillermo Kemmer', 'Arlene Hermann', 'Coleman Runolfsdottir', 'Merl Bins', 'Dr. Easton Lang Sr.', 'Prof. Toy Hodkiewicz', 'Reilly Dooley', 'Nikko Lockman', 'Brody Schroeder', 'Taryn O\'Keefe I', 'Adrianna Kuhlman', '4', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('45', '1', 'Mr. Adolfo Kassulke III', 'Mr. Waino Olson Sr.', 'Deion Gutkowski', 'Amiya Roob I', 'Mrs. Anita O\'Connell II', 'Prof. Casper Mayer DVM', 'Dr. Gage Prohaska PhD', 'Mayra Fahey III', 'Destin Wilkinson', 'Roman Simonis', 'Einar Emard Jr.', 'Dr. Jack Kuphal Sr.', 'Ms. Savanna Crona', 'Tyrique Wilderman III', 'Earlene Yundt', 'Michaela Corkery Jr.', 'Maximus Morar', 'Dr. Dorcas Raynor', 'Vincenza Orn', '1', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('46', '9', 'Shanny King', 'Tyra Crona', 'Ms. Casandra Moore II', 'Johathan Wuckert', 'Mrs. Lenna Hickle I', 'Jaida Lynch', 'Mitchel Kris II', 'Mr. Christop Kshlerin', 'Desiree Mertz', 'Isac Muller', 'Prof. Crystal Grant', 'Mrs. Madie Oberbrunner PhD', 'Miss Anais Kerluke DVM', 'Annabel Parisian', 'Elva Dietrich', 'Ms. Eliza Weissnat', 'Mr. Harrison Conn DDS', 'Dr. Ezra Johnston PhD', 'Dr. Oleta Wolf', '4', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('47', '5', 'Mr. Thad Farrell', 'Ms. Mara Kub PhD', 'Ms. Emie Hamill', 'Bette Lindgren PhD', 'Bobbie Ankunding I', 'Fiona Kautzer', 'Zoey Olson', 'Oswaldo Schumm', 'Prof. Erich Schmidt', 'Matilde Bogisich Jr.', 'Gerard Gleason III', 'Mrs. Antonette Huel DDS', 'Dr. Kamryn Hegmann', 'Mr. Scot Fay V', 'Claudia Brakus', 'Susan Fritsch', 'Kayden Gaylord', 'Dovie Wiegand DDS', 'Dr. Deion Hand I', '1', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('48', '2', 'Prof. Zula Hackett', 'Katarina Kutch', 'Prof. Marjorie Turcotte Sr.', 'Santa Goyette', 'Dereck Effertz', 'Richard Larson', 'Dr. Rebeka Luettgen', 'Mrs. Dolores Pfannerstill', 'Melyna Muller', 'Elbert Streich', 'Lamar Strosin', 'Jonas Murray', 'Michaela Sipes', 'Rodrigo Streich', 'Melany Prosacco', 'Ward Macejkovic', 'Darrion Mayer', 'Dr. Andreanne Kling', 'Samson O\'Hara', '5', '2019-06-05 19:17:12', '2019-06-05 19:17:12');
INSERT INTO `rutas` VALUES ('49', '7', 'Katherine Lebsack I', 'Newell Doyle', 'Prof. Lukas Keebler IV', 'Ms. Felicita Casper', 'Abner Gerhold', 'Alfonso Moen III', 'Donato Langworth', 'Kaci Kirlin', 'Prof. Eli Rogahn', 'Korey Bode', 'Marlen Bartell', 'Mr. Jamie Raynor', 'Prof. Josh Jaskolski MD', 'Dr. Baylee Kilback MD', 'Marcella Romaguera', 'Evert Kshlerin Jr.', 'Kennedi Leuschke', 'Nova Olson', 'Dr. Solon Little', '4', '2019-06-05 19:17:12', '2019-06-05 21:52:46');
INSERT INTO `rutas` VALUES ('50', '46', 'Mr George X', 'Libby Daniel', 'Ruth Pagac', 'Prof. Rosina Prohaska Jr.', 'Kiana Kshlerin', 'Dr. Kraig Sipes Jr.', 'Mr. Camryn Hill Jr.', 'Bartholome Adams', 'Mayra Jerde', 'Mohamed Cole', 'Jailyn Balistreri', 'Mrs. Alisha Sanford V', 'Hester Deckow I', 'Jonatan Beahan Jr.', 'Jordon Roob I', 'Carley Reinger', 'Thea Sawayn', 'Bert Bins', 'Gabe Ziemann', '1', '2019-06-05 19:17:12', '2019-06-05 21:51:56');
INSERT INTO `rutas` VALUES ('51', '1', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', '12', null, null);
